#ifndef PARSED_DATA_H
#define PARSED_DATA_H

//This file is autogenerated from .csv

#define __XXX___ 10 IN
#define __XXX___ 11 IN
#define __XXX___ 12 IN
#define __XXX___ 13 IN
#define __XXX___ 14 IN
#define __XXX___ 15 IN

#endif 