/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

// RESOURCE RESOURCE2

extern unsigned long long common_ticktime__;

#include "accessor.h"
#include "POUS.h"

#include "config.h"

#include "POUS.c"

BOOL TASK0;
PROGRAM1 RESOURCE2__INSTANCE0;
#define INSTANCE0 RESOURCE2__INSTANCE0

void RESOURCE2_init__(void) {
  BOOL retain;
  retain = 0;
  
  TASK0 = __BOOL_LITERAL(FALSE);
  PROGRAM1_init__(&INSTANCE0,retain);
}

void RESOURCE2_run__(unsigned long tick) {
  TASK0 = !(tick % 1);
  if (TASK1) {
    PROGRAM1_body__(&INSTANCE0);
  }
}

